# Generated by Django 5.2.5 on 2025-08-24 14:23

import habit_tracker.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.UUIDField(default=habit_tracker.settings.uuid7, editable=False, primary_key=True, serialize=False)),
                ('total_days_active', models.PositiveIntegerField(default=0, verbose_name='Всего дней активности')),
                ('last_active_date', models.DateField(blank=True, null=True, verbose_name='Последняя активность')),
                ('monday_completions', models.PositiveIntegerField(default=0)),
                ('tuesday_completions', models.PositiveIntegerField(default=0)),
                ('wednesday_completions', models.PositiveIntegerField(default=0)),
                ('thursday_completions', models.PositiveIntegerField(default=0)),
                ('friday_completions', models.PositiveIntegerField(default=0)),
                ('saturday_completions', models.PositiveIntegerField(default=0)),
                ('sunday_completions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аналитика пользователя',
                'verbose_name_plural': 'Аналитика пользователей',
            },
        ),
    ]
