# Generated by Django 5.2.5 on 2025-08-24 14:23

import habit_tracker.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=habit_tracker.settings.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название привычки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('habit_type', models.CharField(choices=[('boolean', 'Да/Нет'), ('numeric', 'Количественная'), ('timer', 'Таймер'), ('negative', 'Отказ от привычки')], default='boolean', max_length=20, verbose_name='Тип привычки')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Целевое значение')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('custom', 'Кастомная')], default='daily', max_length=20, verbose_name='Частота')),
                ('custom_days', models.JSONField(blank=True, default=list, verbose_name='Кастомные дни')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='Время напоминания')),
                ('reminder_days', models.JSONField(blank=True, default=list, verbose_name='Дни напоминаний')),
                ('reminder_enabled', models.BooleanField(default=True, verbose_name='Включить напоминания')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='Текущая серия')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Самая длинная серия')),
                ('total_completions', models.PositiveIntegerField(default=0, verbose_name='Всего выполнений')),
                ('total_skips', models.PositiveIntegerField(default=0, verbose_name='Всего пропусков')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирована')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['group__order', 'group__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HabitGroup',
            fields=[
                ('id', models.UUIDField(default=habit_tracker.settings.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Группа привычек',
                'verbose_name_plural': 'Группы привычек',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.UUIDField(default=habit_tracker.settings.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('completed', 'Выполнено'), ('skipped', 'Пропущено'), ('partial', 'Частично')], default='completed', max_length=20, verbose_name='Статус')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Значение')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Лог привычки',
                'verbose_name_plural': 'Логи привычек',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HabitReminder',
            fields=[
                ('id', models.UUIDField(default=habit_tracker.settings.uuid7, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField(verbose_name='Время')),
                ('days', models.JSONField(default=list, verbose_name='Дни недели')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='Сообщение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
            },
        ),
    ]
