# Generated by Django 5.2.5 on 2025-08-24 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habitgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='habits.habitgroup'),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit'),
        ),
        migrations.AddField(
            model_name='habitreminder',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='habits.habit'),
        ),
        migrations.AlterUniqueTogether(
            name='habitgroup',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('habit', 'date')},
        ),
    ]
