# Generated by Django 5.2.5 on 2025-08-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='habit',
            name='daily_target',
            field=models.PositiveIntegerField(default=1, verbose_name='Цель в день'),
        ),
        migrations.AddField(
            model_name='habit',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='series_goal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цель серии (дней)'),
        ),
        migrations.AddField(
            model_name='habit',
            name='tracking_type',
            field=models.CharField(choices=[('step', 'Пошагово'), ('custom', 'Своё значение')], default='step', max_length=20, verbose_name='Тип отслеживания'),
        ),
    ]
