# Generated by Django 5.2.5 on 2025-08-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_color_habit_daily_target_habit_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования'),
        ),
    ]
