import { StyleSheet } from 'react-native';

export const createModalStyles = (theme: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.divider,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text.primary,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text.primary,
    marginBottom: 12,
  },
  input: {
    backgroundColor: theme.colors.surface,
    color: theme.colors.text.primary,
    fontWeight: '600',
    marginBottom: 8,
    fontSize: 16,
  },
  iconCategories: {
    marginBottom: 16,
    alignItems: 'center', // Центрируем весь контейнер с категориями
  },
  categoryTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.text.secondary,
    marginTop: 16,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  iconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: 300,
    marginHorizontal: 'auto',
    // Создаем строгую сетку 2×6 = 12 иконок в 2 ряда по 6 колонок
    // Ширина: 6 иконок × 44px + 5 отступов × 6px = 294px
  },
  iconItem: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.divider,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconItemSelected: {
    borderColor: theme.colors.text.primary,
    borderWidth: 2,
    backgroundColor: theme.colors.surface,
  },
  iconButton: {
    margin: 0,
    padding: 0,
  },
  colorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  colorItem: {
    width: 40,
    height: 40,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorItemSelected: {
    borderColor: theme.colors.text.primary,
    borderWidth: 3,
  },
  groupOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  groupOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.colors.divider,
    backgroundColor: theme.colors.surface,
  },
  groupOptionSelected: {
    backgroundColor: theme.colors.accent.green,
    borderColor: theme.colors.accent.green,
  },
  groupColor: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 6,
  },
  groupOptionText: {
    fontSize: 14,
    color: theme.colors.text.secondary,
  },
  groupOptionTextSelected: {
    color: theme.colors.text.primary,
    fontWeight: '600',
  },
  advancedToggle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
    marginTop: 16,
  },
  advancedToggleText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  advancedSettings: {
    marginTop: 16,
  },
  goalOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  goalOption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.divider,
    backgroundColor: theme.colors.surface,
  },
  goalOptionSelected: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.text.primary,
  },
  goalOptionText: {
    fontSize: 14,
    color: theme.colors.text.secondary,
  },
  goalOptionTextSelected: {
    color: theme.colors.text.primary,
    fontWeight: '600',
  },
  trackingOptions: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  trackingOption: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.divider,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
  },
  trackingOptionSelected: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.text.primary,
  },
  trackingOptionText: {
    fontSize: 14,
    color: theme.colors.text.secondary,
  },
  trackingOptionTextSelected: {
    color: theme.colors.text.primary,
    fontWeight: '600',
  },
  trackingDescription: {
    fontSize: 12,
    color: theme.colors.text.disabled,
    fontStyle: 'italic',
  },
  targetControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  targetDisplay: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.text.primary,
    borderRadius: 8,
    padding: 12,
  },
  targetText: {
    fontSize: 16,
    color: theme.colors.text.primary,
    textAlign: 'center',
  },
  targetButtons: {
    flexDirection: 'row',
    gap: 4,
  },
  targetButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  targetButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text.primary,
  },
  targetDescription: {
    fontSize: 12,
    color: theme.colors.text.disabled,
    fontStyle: 'italic',
  },
  reminderButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.text.primary,
    borderRadius: 8,
    padding: 12,
  },
  reminderButtonText: {
    fontSize: 16,
    color: theme.colors.text.primary,
  },
  footer: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },
  saveButton: {
    backgroundColor: theme.colors.primary,
  },
  // Цвет текста на кнопке Сохранить
  saveButtonLabel: {
    color: theme.colors.background,
    fontWeight: '700',
  },
  // Стили для центральной иконки с фоном
  centralIconContainer: {
    height: 180,
    width: '100%',
    position: 'relative',
    borderRadius: 16,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.divider,
    marginBottom: 16,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  backgroundIcons: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    alignItems: 'center',
    opacity: 0.15,
    padding: 8,
  },
  backgroundIcon: {
    margin: 2,
  },
  centralIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: theme.colors.background,
    borderWidth: 2,
    borderColor: theme.colors.text.primary,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  centralIcon: {
    margin: 0,
  },
  iconSelectorHidden: {
    display: 'none',
  },
  // Стили для экрана категорий
  categoryDescription: {
    fontSize: 16,
    color: theme.colors.text.secondary,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 22,
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
  },
  categoryItem: {
    width: 100,
    height: 80,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.divider,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
  },
  categoryItemSelected: {
    backgroundColor: theme.colors.background,
    borderColor: theme.colors.text.primary,
  },
  categoryIcon: {
    margin: 0,
    marginBottom: 4,
  },
  categoryText: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    textAlign: 'center',
    fontWeight: '500',
  },
  categoryTextSelected: {
    color: theme.colors.text.primary,
    fontWeight: '600',
  },
  createCustomButton: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 100,
    height: 80,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.text.primary,
    backgroundColor: theme.colors.background,
    marginTop: 16,
  },
  createCustomText: {
    fontSize: 16,
    color: theme.colors.text.primary,
    fontWeight: '600',
    textAlign: 'center',
  },
  saveButtonText: {
    fontSize: 16,
    color: theme.colors.background,
    fontWeight: '600',
    textAlign: 'center',
  },
  saveButtonDisabled: {
    backgroundColor: theme.colors.text.disabled,
  },
  // Стили для кнопки категорий
  categoriesButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.text.primary,
    borderRadius: 8,
    padding: 12,
  },
  categoriesButtonContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectedCategoriesPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  categoryPreviewItem: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryPreviewIcon: {
    margin: 0,
  },
  categoryPreviewCount: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    marginLeft: 4,
  },
  categoriesButtonText: {
    fontSize: 16,
    color: theme.colors.text.primary,
  },
  
  // Стили для модального окна добавления группы
  groupModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  groupModalContent: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 20,
    width: '90%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: theme.colors.divider,
  },
  groupModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.text.primary,
    marginBottom: 20,
    textAlign: 'center',
  },
  groupModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  groupModalButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    marginHorizontal: 5,
  },
  groupModalCancelButton: {
    backgroundColor: theme.colors.surface,
  },
  groupModalSaveButton: {
    backgroundColor: theme.colors.info,
  },
  groupModalCancelButtonText: {
    color: theme.colors.text.secondary,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
  },
  groupModalSaveButtonText: {
    color: theme.colors.text.primary,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
  },
  groupColorPicker: {
    marginBottom: 16,
  },
  groupColorLabel: {
    fontSize: 16,
    color: theme.colors.text.primary,
    marginBottom: 8,
  },
  groupColorOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  groupColorOption: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  groupColorOptionSelected: {
    borderColor: '#333',
    borderWidth: 3,
  },
});
