import { StyleSheet } from 'react-native';
import { colors } from '../constants/appStyles';

export const modalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text.primary,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 12,
  },
  input: {
    backgroundColor: '#000000',
    color: '#ffffff',
    fontWeight: '600',
    marginBottom: 8,
    fontSize: 16,
  },
  iconCategories: {
    marginBottom: 16,
    alignItems: 'center', // Центрируем весь контейнер с категориями
  },
  categoryTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#cccccc',
    marginTop: 16,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  iconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: 300,
    marginHorizontal: 'auto',
    // Создаем строгую сетку 2×6 = 12 иконок в 2 ряда по 6 колонок
    // Ширина: 6 иконок × 44px + 5 отступов × 6px = 294px
  },
  iconItem: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#333333',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconItemSelected: {
    borderColor: '#ffffff',
    borderWidth: 2,
    backgroundColor: '#000000',
  },
  iconButton: {
    margin: 0,
    padding: 0,
  },
  colorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  colorItem: {
    width: 40,
    height: 40,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorItemSelected: {
    borderColor: '#ffffff',
    borderWidth: 3,
  },
  groupOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  groupOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#333333',
    backgroundColor: '#1a1a1a',
  },
  groupOptionSelected: {
    backgroundColor: '#00FF88',
    borderColor: '#00FF88',
  },
  groupColor: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 6,
  },
  groupOptionText: {
    fontSize: 14,
    color: '#cccccc',
  },
  groupOptionTextSelected: {
    color: '#ffffff',
    fontWeight: '600',
  },
  advancedToggle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#333333',
    marginTop: 16,
  },
  advancedToggleText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  advancedSettings: {
    marginTop: 16,
  },
  goalOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  goalOption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#333333',
    backgroundColor: '#1a1a1a',
  },
  goalOptionSelected: {
    backgroundColor: '#000000',
    borderColor: '#ffffff',
  },
  goalOptionText: {
    fontSize: 14,
    color: '#cccccc',
  },
  goalOptionTextSelected: {
    color: '#ffffff',
    fontWeight: '600',
  },
  trackingOptions: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  trackingOption: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#333333',
    backgroundColor: '#1a1a1a',
    alignItems: 'center',
  },
  trackingOptionSelected: {
    backgroundColor: '#000000',
    borderColor: '#ffffff',
  },
  trackingOptionText: {
    fontSize: 14,
    color: '#cccccc',
  },
  trackingOptionTextSelected: {
    color: '#ffffff',
    fontWeight: '600',
  },
  trackingDescription: {
    fontSize: 12,
    color: '#999999',
    fontStyle: 'italic',
  },
  targetControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  targetDisplay: {
    flex: 1,
    backgroundColor: '#000000',
    borderWidth: 1,
    borderColor: '#ffffff',
    borderRadius: 8,
    padding: 12,
  },
  targetText: {
    fontSize: 16,
    color: '#ffffff',
    textAlign: 'center',
  },
  targetButtons: {
    flexDirection: 'row',
    gap: 4,
  },
  targetButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  targetButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  targetDescription: {
    fontSize: 12,
    color: '#999999',
    fontStyle: 'italic',
  },
  reminderButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#000000',
    borderWidth: 1,
    borderColor: '#ffffff',
    borderRadius: 8,
    padding: 12,
  },
  reminderButtonText: {
    fontSize: 16,
    color: '#ffffff',
  },
  footer: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#333333',
  },
  saveButton: {
    backgroundColor: '#00FFFF',
  },
  // Цвет текста на кнопке Сохранить — чёрный
  saveButtonLabel: {
    color: '#000000',
    fontWeight: '700',
  },
  // Стили для центральной иконки с фоном
  centralIconContainer: {
    height: 180,
    width: '100%',
    position: 'relative',
    borderRadius: 16,
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#333333',
    marginBottom: 16,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  backgroundIcons: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    alignItems: 'center',
    opacity: 0.15,
    padding: 8,
  },
  backgroundIcon: {
    margin: 2,
  },
  centralIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#2a2a2a',
    borderWidth: 2,
    borderColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  centralIcon: {
    margin: 0,
  },
  iconSelectorHidden: {
    display: 'none',
  },
  // Стили для экрана категорий
  categoryDescription: {
    fontSize: 16,
    color: colors.text.secondary,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 22,
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
  },
  categoryItem: {
    width: 100,
    height: 80,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
  },
  categoryItemSelected: {
    backgroundColor: colors.background,
    borderColor: '#ffffff',
  },
  categoryIcon: {
    margin: 0,
    marginBottom: 4,
  },
  categoryText: {
    fontSize: 12,
    color: colors.text.secondary,
    textAlign: 'center',
    fontWeight: '500',
  },
  categoryTextSelected: {
    color: colors.text.primary,
    fontWeight: '600',
  },
  createCustomButton: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 100,
    height: 80,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ffffff',
    backgroundColor: colors.background,
    marginTop: 16,
  },
  createCustomText: {
    fontSize: 16,
    color: colors.text.primary,
    fontWeight: '600',
    textAlign: 'center',
  },
  saveButtonText: {
    fontSize: 16,
    color: '#000000',
    fontWeight: '600',
    textAlign: 'center',
  },
  saveButtonDisabled: {
    backgroundColor: '#666666',
  },
  // Стили для кнопки категорий
  categoriesButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#000000',
    borderWidth: 1,
    borderColor: '#ffffff',
    borderRadius: 8,
    padding: 12,
  },
  categoriesButtonContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectedCategoriesPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  categoryPreviewItem: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#1a1a1a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryPreviewIcon: {
    margin: 0,
  },
  categoryPreviewCount: {
    fontSize: 12,
    color: '#cccccc',
    marginLeft: 4,
  },
  categoriesButtonText: {
    fontSize: 16,
    color: '#ffffff',
  },
});
